"""
Schema definitions for the CSE-CIC-IDS2018 dataset.

Column names and types inferred from: 02-14-2018.csv
Timestamp format: dd/MM/yyyy HH:mm:ss
"""

# ---------------------------------------------------------------------------
# Pandas dtype dict (for pd.read_csv)
# ---------------------------------------------------------------------------

PANDAS_DTYPES: dict = {
    "Dst Port":           "Int32",
    "Protocol":           "Int32",
    "Flow Duration":      "Int64",
    "Tot Fwd Pkts":       "Int64",
    "Tot Bwd Pkts":       "Int64",
    "TotLen Fwd Pkts":    "Int64",
    "TotLen Bwd Pkts":    "Int64",
    "Fwd Pkt Len Max":    "float64",
    "Fwd Pkt Len Min":    "float64",
    "Fwd Pkt Len Mean":   "float64",
    "Fwd Pkt Len Std":    "float64",
    "Bwd Pkt Len Max":    "float64",
    "Bwd Pkt Len Min":    "float64",
    "Bwd Pkt Len Mean":   "float64",
    "Bwd Pkt Len Std":    "float64",
    "Flow Byts/s":        "float64",  # may contain "Infinity"
    "Flow Pkts/s":        "float64",
    "Flow IAT Mean":      "float64",
    "Flow IAT Std":       "float64",
    "Flow IAT Max":       "Int64",
    "Flow IAT Min":       "Int64",
    "Fwd IAT Tot":        "Int64",
    "Fwd IAT Mean":       "float64",
    "Fwd IAT Std":        "float64",
    "Fwd IAT Max":        "Int64",
    "Fwd IAT Min":        "Int64",
    "Bwd IAT Tot":        "Int64",
    "Bwd IAT Mean":       "float64",
    "Bwd IAT Std":        "float64",
    "Bwd IAT Max":        "Int64",
    "Bwd IAT Min":        "Int64",
    "Fwd PSH Flags":      "Int32",
    "Bwd PSH Flags":      "Int32",
    "Fwd URG Flags":      "Int32",
    "Bwd URG Flags":      "Int32",
    "Fwd Header Len":     "Int64",
    "Bwd Header Len":     "Int64",
    "Fwd Pkts/s":         "float64",
    "Bwd Pkts/s":         "float64",
    "Pkt Len Min":        "float64",
    "Pkt Len Max":        "float64",
    "Pkt Len Mean":       "float64",
    "Pkt Len Std":        "float64",
    "Pkt Len Var":        "float64",
    "FIN Flag Cnt":       "Int32",
    "SYN Flag Cnt":       "Int32",
    "RST Flag Cnt":       "Int32",
    "PSH Flag Cnt":       "Int32",
    "ACK Flag Cnt":       "Int32",
    "URG Flag Cnt":       "Int32",
    "CWE Flag Count":     "Int32",
    "ECE Flag Cnt":       "Int32",
    "Down/Up Ratio":      "float64",
    "Pkt Size Avg":       "float64",
    "Fwd Seg Size Avg":   "float64",
    "Bwd Seg Size Avg":   "float64",
    "Fwd Byts/b Avg":     "Int32",
    "Fwd Pkts/b Avg":     "Int32",
    "Fwd Blk Rate Avg":   "Int32",
    "Bwd Byts/b Avg":     "Int32",
    "Bwd Pkts/b Avg":     "Int32",
    "Bwd Blk Rate Avg":   "Int32",
    "Subflow Fwd Pkts":   "Int64",
    "Subflow Fwd Byts":   "Int64",
    "Subflow Bwd Pkts":   "Int64",
    "Subflow Bwd Byts":   "Int64",
    "Init Fwd Win Byts":  "Int32",
    "Init Bwd Win Byts":  "Int32",
    "Fwd Act Data Pkts":  "Int64",
    "Fwd Seg Size Min":   "Int32",
    "Active Mean":        "float64",
    "Active Std":         "float64",
    "Active Max":         "Int64",
    "Active Min":         "Int64",
    "Idle Mean":          "float64",
    "Idle Std":           "float64",
    "Idle Max":           "Int64",
    "Idle Min":           "Int64",
    "Label":              "object",
}

# Columns to parse as datetime
PANDAS_PARSE_DATES: list = ["Timestamp"]
TIMESTAMP_FORMAT: str = "%d/%m/%Y %H:%M"

# ---------------------------------------------------------------------------
# PySpark schema (for spark.read.csv)
# ---------------------------------------------------------------------------

def get_spark_schema():
    from pyspark.sql.types import (
        StructType, StructField,
        IntegerType, LongType, DoubleType, StringType,
    )
    return StructType([
        StructField("Dst Port",           IntegerType(), True),
        StructField("Protocol",           IntegerType(), True),
        StructField("Timestamp",          StringType(),  True),
        StructField("Flow Duration",      LongType(),    True),
        StructField("Tot Fwd Pkts",       LongType(),    True),
        StructField("Tot Bwd Pkts",       LongType(),    True),
        StructField("TotLen Fwd Pkts",    LongType(),    True),
        StructField("TotLen Bwd Pkts",    LongType(),    True),
        StructField("Fwd Pkt Len Max",    DoubleType(),  True),
        StructField("Fwd Pkt Len Min",    DoubleType(),  True),
        StructField("Fwd Pkt Len Mean",   DoubleType(),  True),
        StructField("Fwd Pkt Len Std",    DoubleType(),  True),
        StructField("Bwd Pkt Len Max",    DoubleType(),  True),
        StructField("Bwd Pkt Len Min",    DoubleType(),  True),
        StructField("Bwd Pkt Len Mean",   DoubleType(),  True),
        StructField("Bwd Pkt Len Std",    DoubleType(),  True),
        StructField("Flow Byts/s",        DoubleType(),  True),
        StructField("Flow Pkts/s",        DoubleType(),  True),
        StructField("Flow IAT Mean",      DoubleType(),  True),
        StructField("Flow IAT Std",       DoubleType(),  True),
        StructField("Flow IAT Max",       LongType(),    True),
        StructField("Flow IAT Min",       LongType(),    True),
        StructField("Fwd IAT Tot",        LongType(),    True),
        StructField("Fwd IAT Mean",       DoubleType(),  True),
        StructField("Fwd IAT Std",        DoubleType(),  True),
        StructField("Fwd IAT Max",        LongType(),    True),
        StructField("Fwd IAT Min",        LongType(),    True),
        StructField("Bwd IAT Tot",        LongType(),    True),
        StructField("Bwd IAT Mean",       DoubleType(),  True),
        StructField("Bwd IAT Std",        DoubleType(),  True),
        StructField("Bwd IAT Max",        LongType(),    True),
        StructField("Bwd IAT Min",        LongType(),    True),
        StructField("Fwd PSH Flags",      IntegerType(), True),
        StructField("Bwd PSH Flags",      IntegerType(), True),
        StructField("Fwd URG Flags",      IntegerType(), True),
        StructField("Bwd URG Flags",      IntegerType(), True),
        StructField("Fwd Header Len",     LongType(),    True),
        StructField("Bwd Header Len",     LongType(),    True),
        StructField("Fwd Pkts/s",         DoubleType(),  True),
        StructField("Bwd Pkts/s",         DoubleType(),  True),
        StructField("Pkt Len Min",        DoubleType(),  True),
        StructField("Pkt Len Max",        DoubleType(),  True),
        StructField("Pkt Len Mean",       DoubleType(),  True),
        StructField("Pkt Len Std",        DoubleType(),  True),
        StructField("Pkt Len Var",        DoubleType(),  True),
        StructField("FIN Flag Cnt",       IntegerType(), True),
        StructField("SYN Flag Cnt",       IntegerType(), True),
        StructField("RST Flag Cnt",       IntegerType(), True),
        StructField("PSH Flag Cnt",       IntegerType(), True),
        StructField("ACK Flag Cnt",       IntegerType(), True),
        StructField("URG Flag Cnt",       IntegerType(), True),
        StructField("CWE Flag Count",     IntegerType(), True),
        StructField("ECE Flag Cnt",       IntegerType(), True),
        StructField("Down/Up Ratio",      DoubleType(),  True),
        StructField("Pkt Size Avg",       DoubleType(),  True),
        StructField("Fwd Seg Size Avg",   DoubleType(),  True),
        StructField("Bwd Seg Size Avg",   DoubleType(),  True),
        StructField("Fwd Byts/b Avg",     IntegerType(), True),
        StructField("Fwd Pkts/b Avg",     IntegerType(), True),
        StructField("Fwd Blk Rate Avg",   IntegerType(), True),
        StructField("Bwd Byts/b Avg",     IntegerType(), True),
        StructField("Bwd Pkts/b Avg",     IntegerType(), True),
        StructField("Bwd Blk Rate Avg",   IntegerType(), True),
        StructField("Subflow Fwd Pkts",   LongType(),    True),
        StructField("Subflow Fwd Byts",   LongType(),    True),
        StructField("Subflow Bwd Pkts",   LongType(),    True),
        StructField("Subflow Bwd Byts",   LongType(),    True),
        StructField("Init Fwd Win Byts",  IntegerType(), True),
        StructField("Init Bwd Win Byts",  IntegerType(), True),
        StructField("Fwd Act Data Pkts",  LongType(),    True),
        StructField("Fwd Seg Size Min",   IntegerType(), True),
        StructField("Active Mean",        DoubleType(),  True),
        StructField("Active Std",         DoubleType(),  True),
        StructField("Active Max",         LongType(),    True),
        StructField("Active Min",         LongType(),    True),
        StructField("Idle Mean",          DoubleType(),  True),
        StructField("Idle Std",           DoubleType(),  True),
        StructField("Idle Max",           LongType(),    True),
        StructField("Idle Min",           LongType(),    True),
        StructField("Label",              StringType(),  True),
    ])
